channels:
  - conda-forge
  - usgs-astrogeology
  - menpo

dependencies:
  - python >= 3
#  - coveralls
#  - csmapi
#  - cyvlfeat
#  - dill
  - gdal
#  - geoalchemy2
#  - geopandas
#  - hoggorm
#  - imageio
#  - ipykernel
#  - jupyter
#  - knoten
#  - nbsphinx
#  - ncurses
#  - networkx
#  - numpy
#  - opencv <= 3.5
#  - pillow
#  - pip
#  - plio >= 1.1.0
#  - plurmy
#  - psycopg2
#  - pyproj
#  - pytest
#  - pytest-cov
#  - pysis
#  - pvl < 1.0
#  - richdem
#  - scikit-image
#  - scikit-learn
#  - scipy<=1.2.1
#  - shapely
#  - sphinx
#  - sqlalchemy
#  - sqlalchemy-utils
#  - redis-py
#  - usgscsm
#  - vlfeat
# added dependencies one at a time from rtd failures, not in orig env.yml above
  - yaml
