channels:
  - conda-forge
  - usgs-astrogeology
  - menpo

dependencies:
  - python >= 3
  - csmapi
  - cyvlfeat
  - dill
  - geoalchemy2
  - geopandas
  - hoggorm
  - imageio
  - ipykernel
  - jupyter
  - knoten
  - nbsphinx
  - ncurses
  - networkx
  - numpy
  - plio >= 1.1.0
  - plurmy
  - psycopg2
  - pyproj
  - pytest
  - pytest-cov
  - pysis
  - pvl < 1.0
  - richdem
  - scikit-image
  - scikit-learn
  - scipy<=1.2.1
  - shapely
  - sphinx
  - sqlalchemy
  - sqlalchemy-utils
  - usgscsm
  - vlfeat

